openapi: 3.0.0 # Mendefinisikan versi OpenAPI yang digunakan, dalam hal ini adalah versi 3

info: # Blok informasi metadata tentang API
  title: Ambil Semua Data Transaksi API 
  version: 1.0.0 #versi API

tags: # Daftar tag yang digunakan
  - name: Daftar API

parameters: #Daftar parameter yang dapat digunakan untuk semua operasi API
  - in: body # parameter ini berada di body request
    name: body # nama dari parameter
    description: Data transaksi yang akan ditambahkan # deskripsi dari parameter
    required: true #mennadakan bahwa parameter ini wajib diisi 
    schema: #skema dari parameter, mendefinisikan strikter data dari parameter
      type: object # tipe dari skema, dalam hal ini adalah object 
      properties: # adaftar properti yang dapat dimiliki oleh onbject
        item_id: # nama dari properti
          type: integer # tipe dari properti
        date: # nama dari properti
          type: string #tipe dari properti
          format: date-time
        quantity: # nama dari properti
          type: integer # tipe dari properti

responses:  # Daftar response yang dapat diberikan oleh opreasi API
  201: #kode status HTTP untuk response sukses pembuatan resource baru
    descriptions: Data transaksi berhasil ditambahkan # deskripsi respon
    schema:  #skema dari response, mendefinisikan struktur data dari respon
      $ref: '#/definitions/Transaction' #referensi ke definisi 'karyawan'

definitions: #daftar definisi skema yang dapat digunakan di seluruh file
  Transaction: # nama dari definisi skema
    type: object # tipe dari skema, dalam hal ini adalah object 
    properties: # adaftar properti yang dapat dimiliki oleh onbject
      item_id: # nama dari properti
        type: integer # tipe dari properti
      date: # nama dari properti
        type: string #tipe dari properti
        format: date-time
      quantity: # nama dari properti
        type: integer # tipe dari properti
      required: # daftar properti yang wajib ada dalam object
        - item_id #properti ini adalah wajib
        - date #properti ini adalah wajib
        - quantity #properti ini adalah wajib 