openapi: 3.0.0

info: 
  title: Ambil Satu Data Barang
  version: 1.0.0

tags:
  - name: Daftar API

definitions: 
  Transaction:
    type: object
    properties:
      transaction_id:
        type: integer
        description: ID transaksi
      item_id:
        type: integer
        description: ID barang  
      date:
        type: string
        format: date-time
        description: Tanggal transaksi
      quantity:
        type: integer
        description: Jumlah barang
      total_price:
        type: number
        description: Harga total barang

parameters:
  - name: transaction_id
    in: path
    description: ID transaksi yang akan di ambil
    required: true
    type: integer

responses: 
  200:
    description: Data transaksi berdasarkan ID
    schema: 
      $ref: '#/definitions/Transaction'
  400:
    description: Data tidak ditemukan